version: "2"
run:
  issues-exit-code: 1
  tests: true
linters:
  default: all
  disable:
  - asasalint
  - cyclop
  - decorder
  - depguard
  - err113
  - errname
  - errorlint
  - exhaustive
  - exhaustruct
  - forbidigo
  - gochecknoglobals
  - godot
  - godox
  - goheader
  - gomoddirectives
  - grouper
  - importas
  - ireturn
  - lll
  - maintidx
  - makezero
  - mnd
  - nlreturn
  - noctx
  - paralleltest
  - prealloc
  - promlinter
  - revive
  - tagliatelle
  - testifylint
  - testpackage
  - thelper
  - tparallel
  - varnamelen
  - wrapcheck
  - wsl
  settings:
    dupl:
      threshold: 150
    errcheck:
      check-type-assertions: false
      check-blank: false
    goconst:
      min-len: 3
      min-occurrences: 3
    gocritic:
      enabled-checks:
      - boolExprSimplify
      - builtinShadow
      - commentedOutImport
      - emptyFallthrough
      - importShadow
      - indexAlloc
      - methodExprCall
      - nestingReduce
      - ptrToRefParam
      - typeUnparen
      - unnecessaryBlock
      - yodaStyleExpr
    gocyclo:
      min-complexity: 15
    lll:
      line-length: 150
      tab-width: 1
    nakedret:
      max-func-lines: 0
    prealloc:
      simple: true
      range-loops: true
      for-loops: false
    unparam:
      check-exported: false
  exclusions:
    generated: lax
    presets:
    - comments
    - common-false-positives
    - legacy
    - std-error-handling
    paths:
    - third_party$
    - builtin$
    - examples$
issues:
  max-same-issues: 0
  new-from-rev: HEAD~1
  new: false
formatters:
  enable:
  - gofmt
  - gofumpt
  - goimports
  settings:
    gofmt:
      simplify: true
    goimports:
      local-prefixes:
      - github.com
  exclusions:
    generated: lax
    paths:
    - third_party$
    - builtin$
    - examples$
